import Link from 'next/link'
import styles from '../docs.module.css'
import Footer from '../../../components/Footer'

export default function TermsOfUsePage() {
  return (
    <div className={styles.container}>
      <div className={styles.pilotBanner}>
        <span>⚠️</span>
        <span>
          <strong>PILOT ONLY</strong> — This is a pilot program. For questions, contact: <a href="mailto:lesalgad@microsoft.com">Lenin Garcia</a>
        </span>
      </div>

      <header className={styles.header}>
        <div className={styles.headerContent}>
          <Link href="/" className={styles.backLink}>
            ← Back to Home
          </Link>
          <h1 className={styles.title}>📜 Terms of Use</h1>
          <p className={styles.lastUpdated}>Effective Date: January 2025 | Version 1.0.0</p>
        </div>
      </header>

      <main className={styles.main}>
        <div className={styles.content}>
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using the RAI Tools Navigator ("the Tool"), you agree to be bound by these 
            Terms of Use. If you do not agree to these terms, do not use the Tool.
          </p>

          <h2>2. Pilot Program Status</h2>
          <p>
            This Tool is currently in a <strong>pilot program</strong> for initial testing and feedback. 
            It is not a generally available product. The Tool may be modified, updated, or discontinued 
            at any time without prior notice.
          </p>

          <h2>3. Acceptable Use</h2>
          
          <h3>Permitted Uses</h3>
          <ul>
            <li>Learn about Microsoft's Responsible AI tools and frameworks</li>
            <li>Get guidance on selecting appropriate RAI tools for your projects</li>
            <li>Understand best practices for implementing responsible AI</li>
            <li>Provide feedback to improve the Tool</li>
          </ul>

          <h3>Prohibited Uses</h3>
          <ul>
            <li>Generate or process harmful, illegal, or discriminatory content</li>
            <li>Attempt to bypass content safety filters or restrictions</li>
            <li>Share access credentials with unauthorized users</li>
            <li>Reverse engineer or attempt to extract the underlying AI models</li>
            <li>Use automated scripts or bots without authorization</li>
            <li>Impersonate Microsoft or claim official endorsement of outputs</li>
            <li>Make critical business decisions solely based on Tool outputs without human review</li>
          </ul>

          <h2>4. AI-Generated Content Disclaimer</h2>
          <p>
            The Tool uses AI to generate responses. All outputs are:
          </p>
          <ul>
            <li>Generated by machine learning models, not human experts</li>
            <li>Potentially subject to errors, omissions, or inaccuracies</li>
            <li>Not to be considered official Microsoft guidance or documentation</li>
            <li>Subject to the limitations described in the Transparency Note</li>
          </ul>
          <p>
            <strong>Human oversight is required.</strong> Users must exercise independent judgment and 
            verify all recommendations before implementation.
          </p>

          <h2>5. Intellectual Property</h2>
          <p>
            The Tool and its underlying technology are proprietary to Microsoft. All rights reserved. 
            You retain ownership of content you input. You may use the Tool's outputs for your legitimate 
            business purposes, subject to these terms.
          </p>

          <h2>6. Privacy</h2>
          <p>
            Your use of the Tool is subject to the <Link href="/docs/privacy">Privacy Statement</Link>. 
            Do not input confidential, proprietary, or sensitive information unless specifically authorized.
          </p>

          <h2>7. Feedback</h2>
          <p>
            We encourage you to provide feedback about the Tool. Any feedback you provide may be used 
            by Microsoft to improve the Tool and related products. To report issues or concerns, 
            contact <a href="mailto:lesalgad@microsoft.com">lesalgad@microsoft.com</a>.
          </p>

          <h2>8. Limitation of Liability</h2>
          <p>
            THE TOOL IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND. TO THE 
            MAXIMUM EXTENT PERMITTED BY LAW, MICROSOFT SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, 
            SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE TOOL.
          </p>
          <p>
            You acknowledge that this is a pilot tool and accept all risks associated with using 
            pre-release software.
          </p>

          <h2>9. Termination</h2>
          <p>
            Microsoft may suspend or terminate your access to the Tool at any time, for any reason, 
            without notice.
          </p>

          <h2>10. General Provisions</h2>
          <p>
            These Terms are governed by the laws of the State of Washington, USA. These Terms, 
            together with the Privacy Statement and Transparency Note, constitute the entire agreement 
            between you and Microsoft regarding the Tool.
          </p>

          <div className={styles.contactBox}>
            <h3>📧 Contact Information</h3>
            <p><strong>Tool Owner:</strong> Lenin Garcia</p>
            <p><strong>Email:</strong> <a href="mailto:lesalgad@microsoft.com">lesalgad@microsoft.com</a></p>
          </div>

          <div className={styles.relatedDocs}>
            <h3>Related Documentation</h3>
            <div className={styles.docLinks}>
              <Link href="/docs/transparency" className={styles.docLink}>Transparency Note</Link>
              <Link href="/docs/privacy" className={styles.docLink}>Privacy Statement</Link>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}
